// Research guidance is editorial context, not a claim about a company's operations.
export function sectorContext(c,e){
 const topics=[
 [/software|technology|internet|data |cyber|comput|digital|fintech|platform/i,'Technology and software','When researching a technology business, distinguish the product from its delivery model. Software licensing, subscriptions, services, and hardware can describe different customer relationships even when companies operate in the same broad sector. A short public description rarely establishes the revenue model, the ownership of intellectual property, or the customer base.',['Does the company describe a specific product, a service engagement, or a platform connecting other parties?','Which current product pages or dated announcements explain how the offering has changed since founding?','Are the founder biography and company history consistent about the original business and later changes?']],
 [/manufactur|industrial|aerospace|automotive|semiconductor|equipment|chemical|energy/i,'Manufacturing and industrial businesses','For an industrial company, research the actual products and where the business participates in the supply chain. Designing a product, manufacturing it, distributing it, and servicing it are distinct activities. The founding record helps identify the organization, but does not show which facilities, subsidiaries, or product lines it operates today.',['Which current company materials identify its products and customer industries?','Does the public history distinguish the original company from later acquisitions or subsidiaries?','What dated evidence supports claims about facilities, distribution, or operating scale?']],
 [/retail|apparel|fashion|consumer|store|commerce|accessor|brand|floral/i,'Retail and consumer businesses','Consumer-business research should separate the brand customers recognize from the legal organization behind it. A brand may sell directly, through stores, through wholesale partners, or through several channels. The available founding association does not establish the present channel mix or whether ownership has changed.',['Does the company’s official site explain the current products and sales channels?','Is the founder associated with the brand, its original operating company, or a later parent organization?','Which dated business records support the company history rather than repeating an undated biography?']],
 [/restaurant|food|beverage|brew|hospitality|hotel/i,'Food and hospitality businesses','A food or hospitality name can refer to an individual location, a chain, a product brand, or a company licensing its concept. Research the operating model before comparing it with another business. Founding information alone does not show the number of active locations, franchise relationships, or present operating ownership.',['Does the current company website distinguish owned locations from franchised or licensed locations?','What sources identify the original concept and the people credited with establishing it?','Are expansion and location claims tied to a date and an identifiable source?']],
 [/bank|financial|insurance|investment|capital|lending/i,'Financial businesses','Financial-business research requires attention to the specific organization and service described. Similar names can refer to a parent company, an operating subsidiary, or a consumer brand. A founder reference is background information; it does not verify the authorization, registration, or current services of any regulated provider.',['Which legal organization does the official site identify as providing the service?','Are the founding history and the present operating organization clearly distinguished?','Where does the provider direct readers to current registration and service information?']],
 [/media|publish|entertain|film|game|music|production|studio/i,'Media and creative businesses','Creative-business histories often span a studio, a publishing label, individual works, and later corporate owners. Distinguish the founding of the business from the release of a particular product or production. The public description identifies an area of activity but does not establish ownership of individual creative works or current publishing rights.',['Which official catalog or portfolio explains the company’s work?','Does the founding history identify the original organization and any later name changes?','Are credits for a person’s creative work separate from evidence that the person founded the company?']],
 [/biotech|pharma|medical|health|therapeutic/i,'Health and life sciences businesses','A health-company description may concern research, a development-stage product, a service business, or commercial distribution. Those stages have different meanings. A founding association is not evidence of clinical results, regulatory authorization, or the availability of a product. Use dated primary company materials and the appropriate official records when evaluating such claims.',['What does the company currently identify as its stage of development or service scope?','Are product availability and research milestones presented with dates and primary sources?','Does a biography distinguish scientific, executive, advisory, and founding roles?']],
 [/agency|consult|service|marketing|advertis|design|staffing|logistic|transport/i,'Service businesses','For a service business, the useful research question is what the organization delivers and to whom. An agency, consulting firm, staffing provider, or logistics company may work under project, recurring, or transaction arrangements. A short directory description does not establish the firm’s present specialties, customer relationships, or capacity.',['Which current service pages define the work a customer can actually purchase?','Does the company history connect the founding team to the same organization named in the reference record?','Which public case studies or announcements help explain the business without assuming private client or revenue information?']]
 ];
 const t=topics.find(x=>x[0].test(c.description));if(!t)return '';
 return `<h2>Research context: ${e(t[1])}</h2><p>${e(t[2])}</p><h3>Questions for researching ${e(c.name)}</h3><ul>${t[3].map(q=>'<li>'+e(q)+'</li>').join('')}</ul><p>This sector context is a reading guide based on the company’s recorded description. It does not attribute a particular business model or capability to ${e(c.name)} without supporting evidence.</p>`;
}
