// Collections use published, sourced growth profiles; ordering is never a quality score.
export function buildCollections({owners,industries,industryCopy,write,e,slug,cards,bread,aeBanner,BASE}){
 const groups=[
  {slug:'northeast',name:'Northeast',states:['Connecticut','Maine','Massachusetts','New Hampshire','Rhode Island','Vermont','New Jersey','New York','Pennsylvania'],intro:'Use these profiles to explore founders associated with companies in the Northeast. Compare each company’s service, public growth context, and recorded location rather than assuming neighboring companies share the same operating model.',questions:['Which parts of the business operate outside the recorded headquarters?','Who keeps the state-by-state record of people, property, and activity?','How does the business coordinate an existing local team with additional advisory work?']},
  {slug:'south',name:'South',states:['Delaware','Florida','Georgia','Maryland','North Carolina','South Carolina','Virginia','West Virginia','Kentucky','Tennessee','Alabama','Mississippi','Louisiana','Oklahoma','Texas','Arkansas'],intro:'This collection connects founders across the South through publicly reported company growth records. Read the profile to distinguish the company’s actual product or service from a broad industry label and its recorded headquarters from its customer footprint.',questions:['Does the company deliver work from one location or across several markets?','Which purchases, projects, or hiring plans need a documented decision timeline?','Who coordinates operating cash needs with owner compensation and investment plans?']},
  {slug:'midwest',name:'Midwest',states:['Illinois','Indiana','Iowa','Kansas','Michigan','Minnesota','Missouri','Nebraska','North Dakota','Ohio','South Dakota','Wisconsin'],intro:'Explore Midwest founders across the sectors represented in our sourced growth profiles. These records provide a starting point for understanding companies and the people publicly associated with building them; they do not measure business quality or current wealth.',questions:['What does the company sell, and what drives its delivery costs?','Which assets and records support the next investment decision?','How are the company’s reinvestment plans coordinated with the owner’s personal cash needs?']},
  {slug:'west',name:'West',states:['Alaska','Arizona','California','Colorado','Hawaii','Idaho','Montana','Nevada','New Mexico','Oregon','Utah','Washington','Wyoming'],intro:'Meet founders associated with Western companies in the publicly researched growth library. The collection combines each recorded location with a source-backed description, so readers can follow the evidence into the full profile and company page.',questions:['Where are the team, property interests, and customers actually located?','What changes if the business expands or hires beyond its headquarters state?','Which owner and company decisions should be reviewed together before a commitment?']}
 ];
 const collections=[];
 function publish(id,title,intro,selected,questions,selection){
  const sorted=[...selected].sort((a,b)=>a.name.localeCompare(b.name));
  if(sorted.length<3)return;
  const p='/collections/'+id+'/',desc=intro;
  const listSchema={'@type':'ItemList',name:title,numberOfItems:sorted.length,itemListElement:sorted.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,url:BASE+'/owners/'+x.slug+'/'}))};
  const evidence=sorted.map(x=>`<li><a href="/owners/${x.slug}/">${e(x.name)}</a> · ${e(x.company)} · ${e(x.location)}. ${e(x.service[0].toUpperCase()+x.service.slice(1))}. ${x.sources.map(s=>`<a href="${e(s.url)}">${e(s.title)}</a>`).join('; ')}.</li>`).join('');
  write(p,title,desc,`<div class="wrap"><section class="page-head">${bread([['Founder collections','/collections/'],[title,null]])}<span class="eyebrow">AE Tax Advisors · Founder research</span><h1>${e(title)}</h1><p class="lede">${e(intro)}</p></section><article class="prose"><h2>How this collection was selected.</h2><p>${e(selection)} Profiles are alphabetical, with no performance score or claim that these founders are the best in their region or sector. Each profile explains the public source and its historical revenue eligibility basis.</p><p>A founder role does not establish current equity ownership. A historical growth record is not a current revenue estimate, valuation, or measure of personal income. Inclusion does not establish an AE Tax Advisors client relationship.</p></article>${cards(sorted)}<section class="section"><article class="prose"><h2>Read the source behind each profile.</h2><ol>${evidence}</ol><h2>Questions for the next business chapter.</h2><p>These are preparation prompts for an owner conversation, not conclusions about any founder listed above.</p><ol>${questions.map(q=>`<li>${e(q)}</li>`).join('')}</ol><h2>AE Tax Advisors: connect the business and owner decisions.</h2><p>AE Tax Advisors owns and publishes Business Owner Index. Explore <a href="/ae-tax-advisors/">AE’s advisory approach</a>, <a href="/resources/">owner preparation resources</a>, and <a href="/tax-strategists/">the discovery conversation</a> when a business, property, or ownership decision needs additional analysis.</p><p><a href="/collections/">Browse all founder collections</a> or <a href="/editorial-standards/">read our editorial standards</a>.</p></article></section><div class="section">${aeBanner()}</div></div>`,{lastmod:'2026-10-10',schema:[listSchema]});
  collections.push({p,title,desc,count:sorted.length});
 }
 for(const g of groups){const selected=owners.filter(p=>g.states.some(state=>p.location.endsWith(', '+state)));publish(g.slug+'-business-founders',`${selected.length} Business Founders to Explore in the ${g.name}`,g.intro,selected,g.questions,'Selected from published growth profiles whose recorded company location ends in a state within the '+g.name+' region. Records with an unconfirmed city or only a United States location are excluded from regional collections.');}
 for(const industry of industries){const selected=owners.filter(p=>p.industry===industry),context=industryCopy[industry];publish(slug(industry)+'-founders',`${selected.length} ${industry} Founders to Explore`,context.intro,selected,context.focus.map(f=>'How does your current team address '+f.toLowerCase()+'?'),'Selected from published growth profiles assigned to the '+industry+' category. The collection includes all published growth profiles in that category, rather than presenting an arbitrary top-ten ranking.');}
 const decisions=[
 ['Owner compensation','Record salary, distributions, benefits, and cash needs separately. Bring your existing payroll arrangement and ask what work a compensation review would include.'],
 ['Entity structure','List every entity, its owners, and its business purpose. Explain what is changing before asking whether an entity review would be useful.'],
 ['Equipment and property','Describe the proposed purchase, business use, financing, and timing. Ask which records and specialist inputs your team needs before evaluating alternatives.'],
 ['Business and rental interests','Map the operating business alongside property holdings and the professionals handling each. Ask how responsibilities and records would be coordinated.'],
 ['Retirement and benefits','Bring the current plan, staffing context, owner goals, and implementation deadline. Discuss what analysis and administration would be separately scoped.'],
 ['Acquisition or ownership transition','Explain the proposed transaction and what has already been committed. Coordinate the advisory conversation with legal and deal professionals while decisions remain open.'],
 ['Year-round planning cadence','Identify when projections, decisions, filings, and implementation checks are needed. Assign a responsible person to each milestone and confirm the agreed support period.']
 ];
 write('/collections/business-owner-tax-planning-checklist/','7 Tax Planning Conversations for Business Owners | AE Tax Advisors','Prepare seven business owner planning conversations with AE Tax Advisors: compensation, entities, property, retirement, transactions, and ongoing coordination.',`<div class="wrap"><section class="page-head"><span class="eyebrow">AE Tax Advisors · National owner resource</span><h1>7 tax planning conversations for your next business chapter.</h1><p class="lede">Bring the decisions ahead into one conversation. This checklist helps established owners explain the work they need before choosing an advisory engagement with AE Tax Advisors.</p></section><article class="prose"><ol>${decisions.map(([h,t])=>`<li><h2>${e(h)}</h2><p>${e(t)}</p></li>`).join('')}</ol><h2>Prepare one brief before the call.</h2><p>Write down the business activity, entities, states, property interests, current team, and next decision deadline. Keep confidential records for a secure process agreed directly with the advisor. At discovery, discuss fit, requested deliverables, implementation responsibilities, and fees.</p><p><a href="/ae-tax-advisors/">Meet AE Tax Advisors</a>, <a href="/tax-strategists/">prepare for a discovery conversation</a>, or <a href="/resources/">explore detailed owner checklists</a>. Recommendations depend on the facts and a professional engagement.</p><h2>About this checklist.</h2><p>Business Owner Index is owned and published by AE Tax Advisors. This is general engagement preparation, not individualized tax advice. It does not prescribe a tax treatment or promise savings.</p><p><a href="/collections/">Browse founder collections</a>.</p></article><div class="section">${aeBanner()}</div></div>`,{lastmod:'2026-10-10',article:true,schema:[{'@type':'Article',headline:'7 tax planning conversations for your next business chapter',datePublished:'2026-10-10',dateModified:'2026-10-10',author:{'@id':BASE+'/#publisher'}}]});
 collections.push({p:'/collections/business-owner-tax-planning-checklist/',title:'7 Tax Planning Conversations for Business Owners',desc:'A practical national owner checklist from AE Tax Advisors.',count:7});
 write('/collections/','Regional Founder Lists & Owner Checklists | AE Tax Advisors','Explore sourced founder collections by region and industry, plus owner planning checklists published by AE Tax Advisors.',`<div class="wrap"><section class="page-head"><span class="eyebrow">AE Tax Advisors · Research collections</span><h1>Explore founders by region and industry.</h1><p class="lede">Sourced lists connect the people, the businesses, and the records behind their stories. Use the owner checklists to prepare for your own next decision.</p></section><div class="guide-grid">${collections.map(c=>`<article class="guide-card"><h2><a href="${c.p}">${e(c.title)}</a></h2><p>${e(c.desc)}</p><a class="text-link" href="${c.p}">Explore this collection ↗</a></article>`).join('')}</div><div class="section">${aeBanner()}</div></div>`,{lastmod:'2026-10-10'});
 return collections.length+1;
}
